#设置一天运行多次.避开高峰分钟段(如每小时的07、23、37、53)。
#因为工作流延迟触发时超过下一个触发时间，则下一个触发时间就不会执行了。因此执行间隔设置小一点
name: 溢价率交易提醒

on:
#每个小时各四次(每小时2次就行)
  schedule:
    #- cron: '07 1 * * 1-5' #9/07  
    #- cron: '23 1 * * 1-5' #9/23
    #- cron: '37 1 * * 1-5' #9/37
    #- cron: '53 1 * * 1-5' #9/53
    #- cron: '07 2 * * 1-5' #10/07
    #- cron: '23 2 * * 1-5' #10/23
    #- cron: '37 2 * * 1-5' #10/37
    - cron: '53 2 * * 1-5' #10/53
    - cron: '07 3 * * 1-5' #11/07
    #- cron: '23 3 * * 1-5' #11/23
    #- cron: '37 3 * * 1-5' #11/37
    #- cron: '53 3 * * 1-5' #11/53
    #- cron: '07 5 * * 1-5' #13/07
    #- cron: '23 5 * * 1-5' #13/23
    #- cron: '37 5 * * 1-5' #13/37
    #- cron: '53 5 * * 1-5' #13/53
    #- cron: '07 6 * * 1-5' #14/07
    #- cron: '23 6 * * 1-5' #14/23
    #- cron: '37 6 * * 1-5' #14/37
    #- cron: '53 6 * * 1-5' #14/53
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare requests

    - name: Run python script
      run: python Premium_Trade_Warn.py
